package com.emailmessenger.repository;

import com.emailmessenger.domain.WaitlistEntry;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest
class WaitlistEntryRepositoryTest {

    @Autowired
    WaitlistEntryRepository repo;

    @Test
    void savesEntryAndChecksExistence() {
        repo.save(new WaitlistEntry("user@example.com"));

        assertThat(repo.existsByEmail("user@example.com")).isTrue();
        assertThat(repo.existsByEmail("other@example.com")).isFalse();
    }

    @Test
    void duplicateEmailViolatesUniqueConstraint() {
        repo.save(new WaitlistEntry("dup@example.com"));
        repo.flush();

        assertThatThrownBy(() -> {
            repo.saveAndFlush(new WaitlistEntry("dup@example.com"));
        }).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void createdAtIsPopulatedOnSave() {
        var entry = repo.save(new WaitlistEntry("ts@example.com"));
        assertThat(entry.getCreatedAt()).isNotNull();
    }

    @Test
    void referralTokenIsAutoGeneratedAndUnique() {
        var a = repo.save(new WaitlistEntry("a@example.com"));
        var b = repo.save(new WaitlistEntry("b@example.com"));

        assertThat(a.getReferralToken()).isNotBlank();
        assertThat(b.getReferralToken()).isNotBlank();
        assertThat(a.getReferralToken()).isNotEqualTo(b.getReferralToken());
    }

    @Test
    void findByReferralTokenReturnsEntry() {
        var saved = repo.save(new WaitlistEntry("lookup@example.com"));

        var found = repo.findByReferralToken(saved.getReferralToken());

        assertThat(found).isPresent();
        assertThat(found.get().getEmail()).isEqualTo("lookup@example.com");
    }

    @Test
    void findByReferralTokenReturnsEmptyForUnknown() {
        assertThat(repo.findByReferralToken("not-a-real-token")).isEmpty();
    }

    @Test
    void countByIdLessThanReturnsZeroForFirstEntry() {
        var first = repo.saveAndFlush(new WaitlistEntry("first@example.com"));
        assertThat(repo.countByIdLessThan(first.getId())).isZero();
    }

    @Test
    void countByIdLessThanCountsPriorEntries() {
        var first = repo.saveAndFlush(new WaitlistEntry("first@example.com"));
        repo.saveAndFlush(new WaitlistEntry("second@example.com"));
        var third = repo.saveAndFlush(new WaitlistEntry("third@example.com"));

        assertThat(repo.countByIdLessThan(first.getId())).isZero();
        assertThat(repo.countByIdLessThan(third.getId())).isEqualTo(2);
    }
}
