-- Saved searches let a user pin a specific query+sender+filter combination so
-- "everything from Ada in the last 30 days" is one click from the rail. Powers
-- the EPIC-08 retention loop: Free=1 saved search is the upgrade nudge, paid
-- tiers are unlimited.
CREATE TABLE saved_searches (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id             BIGINT       NOT NULL,
    name                 VARCHAR(80)  NOT NULL,
    query_text           VARCHAR(200),
    sender_email         VARCHAR(254),
    since_preset         VARCHAR(10),
    require_unread       BOOLEAN      NOT NULL DEFAULT FALSE,
    require_attachments  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saved_searches_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT uq_saved_searches_owner_name UNIQUE (owner_id, name)
);

CREATE INDEX idx_saved_searches_owner ON saved_searches (owner_id, created_at DESC);
