-- Tracks per-user digest email state for EPIC-08 Milestone 3: the weekly
-- "what's new in your saved searches" email. One row per user, created
-- lazily the first time the digest runs. `opt_out_token` is a long random
-- string surfaced in every footer so the user can unsubscribe with a GET
-- (no auth) and we can revoke quickly. `last_sent_at` lets the scheduler
-- skip users we already emailed this cycle when it runs more often than
-- the intended weekly cadence (a redeploy or manual trigger), and lets
-- the operator audit who got mail when.
CREATE TABLE digest_email_preferences (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    opt_out_token VARCHAR(64)  NOT NULL,
    opted_out     BOOLEAN      NOT NULL DEFAULT FALSE,
    last_sent_at  TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_digest_prefs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_digest_prefs_user UNIQUE (user_id),
    CONSTRAINT uq_digest_prefs_token UNIQUE (opt_out_token)
);
