-- EPIC-09 Milestone 1: password reset via emailed token.
--
-- One row per outstanding reset link. The plaintext token (32 random
-- bytes → URL-safe base64) is emailed to the user and never written to
-- the DB; we store SHA-256(token) as 64-char hex so that even a full
-- table dump cannot be replayed to take over accounts. A user can have
-- multiple rows (a fast re-request before the prior one expires), but
-- consumeToken() revokes every other outstanding row for the same user
-- so the most recent link is the only one that still works.
--
-- `used_at` (single-use) and `expires_at` (1-hour TTL) are both
-- enforced in the service layer so the same SQL works for resends and
-- audit. `expires_at` is NOT NULL so a malformed insert can't yield an
-- effectively-immortal token.
CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    used_at    TIMESTAMP,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_password_reset_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_user ON password_reset_tokens (user_id);
