-- EPIC-09 Milestone 2: email verification on signup.
--
-- Two parts:
--
--   1. `users.email_verified_at` — null while the address is unconfirmed,
--      set to the verification timestamp when the user clicks through.
--      We backfill every existing row to NOW() so users who registered
--      before this milestone (i.e. the developers and any pre-1.0
--      account) are treated as already-verified — flipping them to
--      unverified retroactively would slap them with a banner they have
--      no recovery path for and would silently re-gate any feature that
--      keys off verification.
--
--   2. `email_verifications` token table — same shape as
--      password_reset_tokens. Plaintext is 32 random bytes URL-safe
--      base64, never stored; the DB keeps SHA-256(token) hex so a dump
--      can't be replayed. Tokens are single-use (used_at) and expire in
--      24 hours (longer than password reset because the verification
--      mail might sit unread for a day, and the only thing that gates
--      on verification is non-destructive — paid feature unlocks and a
--      soft banner — so a slightly longer TTL doesn't add risk).
ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMP;
UPDATE users SET email_verified_at = CURRENT_TIMESTAMP WHERE email_verified_at IS NULL;

CREATE TABLE email_verifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    used_at    TIMESTAMP,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_verifications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_email_verifications_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_email_verifications_user ON email_verifications (user_id);
