-- EPIC-09 Milestone 4: login throttling + auth audit log.
--
-- One row per authentication-shaped event for the "recent account
-- activity" panel on /account and for the brute-force throttle. We
-- always record the *email attempted* (lower-cased), so a failure for a
-- non-existent address still produces a row to count against the IP
-- throttle. `user_id` is nullable so failures for unknown emails don't
-- need a synthetic user. `ip_address` is wide enough for an IPv6
-- address (45 chars) but nullable so a programmatic call site without a
-- request context (re-auth from request.login() right after register)
-- doesn't break the insert.
--
-- Event types kept open as VARCHAR rather than a CHECK constraint
-- because the service layer is the single writer (no SQL-level inserts
-- from anywhere else) and adding a new event type shouldn't require a
-- new migration.
--
-- Indexes:
--   * (user_id, created_at DESC) drives the per-user "last 10 events"
--     panel on /account.
--   * (email, created_at) and (ip_address, created_at) drive the throttle
--     counts ("how many LOGIN_FAILUREs for this email/IP in the last
--     N minutes").
CREATE TABLE auth_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    email       VARCHAR(254) NOT NULL,
    event_type  VARCHAR(32)  NOT NULL,
    ip_address  VARCHAR(45),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_events_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_auth_events_user_created  ON auth_events (user_id, created_at);
CREATE INDEX idx_auth_events_email_created ON auth_events (email, created_at);
CREATE INDEX idx_auth_events_ip_created    ON auth_events (ip_address, created_at);
