-- Participants: deduplicated by normalized email address
CREATE TABLE participants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(254)  NOT NULL,
    display_name VARCHAR(255),
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_participants_email UNIQUE (email)
);

-- Email threads: groups messages by Message-ID / In-Reply-To chain
CREATE TABLE email_threads (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject         VARCHAR(998)  NOT NULL,
    root_message_id VARCHAR(998),
    message_count   INT           NOT NULL DEFAULT 0,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_email_threads_root_message_id UNIQUE (root_message_id)
);

-- Messages: one email per row
CREATE TABLE messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id         BIGINT       NOT NULL,
    message_id_header VARCHAR(998),
    in_reply_to       VARCHAR(998),
    sender_id         BIGINT       NOT NULL,
    subject           VARCHAR(998),
    body_plain        TEXT,
    body_html         TEXT,
    sent_at           TIMESTAMP    NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_thread  FOREIGN KEY (thread_id) REFERENCES email_threads (id),
    CONSTRAINT fk_messages_sender  FOREIGN KEY (sender_id) REFERENCES participants (id),
    CONSTRAINT uq_messages_header  UNIQUE (message_id_header)
);

-- Message recipients: TO / CC / BCC per message
CREATE TABLE message_recipients (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id     BIGINT      NOT NULL,
    participant_id BIGINT      NOT NULL,
    recipient_type VARCHAR(3)  NOT NULL,
    CONSTRAINT fk_mr_message     FOREIGN KEY (message_id)     REFERENCES messages (id),
    CONSTRAINT fk_mr_participant FOREIGN KEY (participant_id) REFERENCES participants (id)
);

-- Attachments
CREATE TABLE attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT        NOT NULL,
    filename    VARCHAR(255)  NOT NULL,
    mime_type   VARCHAR(127),
    size_bytes  BIGINT,
    blob_ref    VARCHAR(2048),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachments_message FOREIGN KEY (message_id) REFERENCES messages (id)
);

-- Indexes for common query patterns
CREATE INDEX idx_messages_thread_id          ON messages          (thread_id);
CREATE INDEX idx_messages_sent_at            ON messages          (sent_at DESC);
CREATE INDEX idx_message_recipients_msg_id   ON message_recipients (message_id);
CREATE INDEX idx_message_recipients_part_id  ON message_recipients (participant_id);
CREATE INDEX idx_attachments_message_id      ON attachments        (message_id);
CREATE INDEX idx_email_threads_updated_at    ON email_threads      (updated_at DESC);
