-- EPIC-15 Milestone 2: scaffold the Team model and the invite flow so
-- "Invite a teammate" can become a real action in the onboarding
-- progress card. Three tables:
--
--   teams           — one row per team. For now a team is owned by
--                     exactly one user (UNIQUE on owner_user_id); a
--                     later EPIC may relax this when sharing lands.
--   team_members    — junction table. The owner row is created at the
--                     same time as the team. Invitees are inserted on
--                     accept. UNIQUE (team_id, user_id) prevents the
--                     same user being added twice.
--   team_invites    — outstanding invite tokens. Plaintext token (32
--                     random bytes -> URL-safe base64) is emailed and
--                     never stored; the DB keeps SHA-256(token) hex so
--                     a dump can't be replayed. Tokens are single-use
--                     (accepted_at) and TTL'd in the service layer; the
--                     `revoked_at` column lets the inviter cancel a
--                     pending invite without deleting the audit trail.
CREATE TABLE teams (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)  NOT NULL,
    owner_user_id BIGINT        NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_teams_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT uq_teams_owner_user UNIQUE (owner_user_id)
);

CREATE TABLE team_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id   BIGINT       NOT NULL,
    user_id   BIGINT       NOT NULL,
    role      VARCHAR(16)  NOT NULL,
    joined_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_team_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_team_members_team_user UNIQUE (team_id, user_id)
);

CREATE INDEX idx_team_members_user ON team_members (user_id);

CREATE TABLE team_invites (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id            BIGINT       NOT NULL,
    invited_by_user_id BIGINT       NOT NULL,
    invitee_email      VARCHAR(254) NOT NULL,
    token_hash         VARCHAR(64)  NOT NULL,
    expires_at         TIMESTAMP    NOT NULL,
    accepted_at        TIMESTAMP,
    revoked_at         TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_team_invites_team       FOREIGN KEY (team_id)            REFERENCES teams (id),
    CONSTRAINT fk_team_invites_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users (id),
    CONSTRAINT uq_team_invites_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_team_invites_team          ON team_invites (team_id);
CREATE INDEX idx_team_invites_invited_by    ON team_invites (invited_by_user_id);
CREATE INDEX idx_team_invites_invitee_email ON team_invites (invitee_email);
