-- EPIC-16 Milestone 1: internal team notes on a thread.
--
-- A note is a private comment pinned to an email_thread, visible only
-- to members of the team that owns the thread (Team / Enterprise plan
-- gating is enforced in the service layer — the DB just models the
-- relationships so future milestones can lift visibility to all team
-- members without a schema change).
--
-- Columns:
--   thread_id      — the conversation the note is attached to.
--   team_id        — denormalized so future cross-user visibility
--                    queries don't need to walk through email_threads.owner.
--   author_user_id — who wrote it (renders attribution next to the body).
--   body           — TEXT; service caps at 4 KB so a runaway paste can't
--                    fill the column. No HTML; rendered as plain text.
CREATE TABLE thread_notes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id      BIGINT    NOT NULL,
    team_id        BIGINT    NOT NULL,
    author_user_id BIGINT    NOT NULL,
    body           TEXT      NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_thread_notes_thread FOREIGN KEY (thread_id)      REFERENCES email_threads (id),
    CONSTRAINT fk_thread_notes_team   FOREIGN KEY (team_id)        REFERENCES teams (id),
    CONSTRAINT fk_thread_notes_author FOREIGN KEY (author_user_id) REFERENCES users (id)
);

CREATE INDEX idx_thread_notes_thread ON thread_notes (thread_id);
CREATE INDEX idx_thread_notes_team   ON thread_notes (team_id);
