-- EPIC-16 Milestone 4: log of plan transitions for the operator dashboard.
--
-- We need to know how many of this window's TEAM/ENTERPRISE conversions
-- came directly from FREE (a brand-new paid customer) versus PERSONAL
-- (an existing paying customer who upgraded to the shared-inbox tier).
-- The local Subscription row only stores the *current* plan, so without
-- a history table the "Free→Team vs Personal→Team" split on the
-- /admin/revenue Team-plan adoption card cannot be computed.
--
-- The BillingService writes one row per accepted plan transition (it
-- doesn't log when the plan is unchanged or when the same plan is
-- re-selected mid-checkout). FREE is the from_plan for first-ever
-- paid checkouts; the to_plan is always the plan the user is moving
-- to (FREE, PERSONAL, TEAM, ENTERPRISE).
CREATE TABLE plan_change_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    from_plan       VARCHAR(32)  NOT NULL,
    to_plan         VARCHAR(32)  NOT NULL,
    occurred_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pce_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions (id),
    CONSTRAINT fk_pce_user         FOREIGN KEY (user_id)         REFERENCES users (id)
);

CREATE INDEX idx_pce_to_plan_at ON plan_change_events (to_plan, occurred_at);
CREATE INDEX idx_pce_user       ON plan_change_events (user_id);
