-- Waitlist entries: email lead capture before auth ships
CREATE TABLE waitlist_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(254) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_waitlist_entries_email UNIQUE (email)
);

CREATE INDEX idx_waitlist_entries_created_at ON waitlist_entries (created_at DESC);
