-- Application users (authenticates into the app, owns mailboxes & threads).
-- Distinct from `participants`, which model email senders/recipients seen in
-- imported messages and which may or may not correspond to a registered user.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    display_name  VARCHAR(255),
    enabled       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_email ON users (email);

-- Persistent remember-me token store (Spring Security JdbcTokenRepositoryImpl schema).
CREATE TABLE persistent_logins (
    username  VARCHAR(64)   NOT NULL,
    series    VARCHAR(64)   PRIMARY KEY,
    token     VARCHAR(64)   NOT NULL,
    last_used TIMESTAMP     NOT NULL
);
