-- One Subscription row per user, populated lazily.
-- Created at /billing/checkout start with status='incomplete' so we always have
-- a stable stripe_customer_id, then mutated by Stripe webhook events.
CREATE TABLE subscriptions (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT       NOT NULL,
    plan                    VARCHAR(32),
    status                  VARCHAR(32)  NOT NULL,
    stripe_customer_id      VARCHAR(255) NOT NULL,
    stripe_subscription_id  VARCHAR(255),
    stripe_price_id         VARCHAR(255),
    trial_ends_at           TIMESTAMP,
    current_period_end      TIMESTAMP,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_subscriptions_user UNIQUE (user_id),
    CONSTRAINT uq_subscriptions_stripe_sub UNIQUE (stripe_subscription_id)
);

CREATE INDEX idx_subscriptions_customer ON subscriptions (stripe_customer_id);
