-- IMAP mailbox connections: one per user-supplied account, encrypted at rest.
-- The encrypted password is what the user provides (typically an app password)
-- so we can re-open the IMAP session for scheduled polling once that ships.
CREATE TABLE mail_accounts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL,
    host                 VARCHAR(255) NOT NULL,
    port                 INT          NOT NULL,
    ssl                  BOOLEAN      NOT NULL,
    username             VARCHAR(254) NOT NULL,
    password_ciphertext  TEXT         NOT NULL,
    last_synced_at       TIMESTAMP,
    last_sync_error      VARCHAR(500),
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mail_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_mail_accounts_user_host_user UNIQUE (user_id, host, username)
);

CREATE INDEX idx_mail_accounts_user_id ON mail_accounts (user_id);
